site_name: eBPF notes
theme:
  language: en
  name: material
  custom_dir: overrides
extra:
  alternate:
    - name: English
      link: / 
      lang: en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - git-authors
  - git-revision-date-localized
nav:
    - index.md
    - Overview:
        - overview/articles.md
        - overview/linux-kernel.md
    - 'Getting Started':
        - getting-started/hello-world.md
    - 'Go and ebpf':
        - 'Setup': 'golang-ebpf/setup.md'
    - takeaway.md
